### PR TITLE
Fix/29

### LINKED ISSUE #29: LifterLMS Labs prevents Beaver Builder from enabling Certificated and Awarded Certificate Post Type integration
### Reproduction Steps

+ Install LifterLMS Labs
+ Install Beaver Builder Page builder
+ Enable the Beaver Builder page builder in LifterLMS Labs
+ Head into Beaver Builder Settings->Post Types
+ HS-213476

### Expected Behavior

+ Certificates and Awarded certificates should be visible to enable the builder integration

### Actual Behavior

+ With the LifterLMS Labs integration enabled with Beaver Builder the Certificate post types are not an option

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natie.myliftersite.com
Site Url: https://natie.myliftersite.com
Login Url: https://natie.myliftersite.com/wp-login.php
Version: 6.1.1
Debug Mode: Yes
Debug Log: Yes
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: No


Settings
-------------------------------------------

Version: 7.0.1
Db Version: 7.0.1
Course Catalog: Course Catalog (#120) [https://natie.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#121) [https://natie.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#123) [https://natie.myliftersite.com/dashboard/]
Checkout Page: Purchase (#122) [https://natie.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: MXN
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+trial@lifterlms.com
Email From Name: My LifterLMS Trial Site
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.41
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.28
Software: Apache/2.4.55 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0


Theme
-------------------------------------------

Name: Beaver Builder – Child
Version: 1.0
Themeuri: https://www.causelabs.com/
Authoruri: https://www.causelabs.com/
Template: bb-theme
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Beaver Builder Plugin (Lite Version): 2.6.2.3
LifterLMS: 7.0.1
LifterLMS Labs: 1.6.0
User Switching: 1.7.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

### This issue has been recreated:

+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### PR DESCRIPTION
**Pull request by actuallyakash**
## Description

Fixes #29 

## How has this been tested?
Manually.

## Types of changes
Bug fix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
hey @actuallyakash thanks
I see this PR includes https://github.com/gocodebox/lifterlms-labs/pull/31 too, can you clean this one with only the code and the commits related to the issue it aims to fix?
Thanks!

**Comment by eri-trabiccolo** [comment]
Ohh I see the problem is that you pushed that added to switch favorites to the `dev` branch.
~I'm gonna fix that~ Fixed now.
Can you rebase this PR agains the actual `dev` branch?
Thanks!

**Comment by eri-trabiccolo** [comment]
@actuallyakash bump :)

**Comment by actuallyakash** [comment]
Hey @eri-trabiccolo 

I've created a [new PR](https://github.com/gocodebox/lifterlms-labs/pull/38) against the dev with the right commits.

(Closing the PR)

**Pull request closed without merging**
