### PR TITLE
Feature/favorites

### PR DESCRIPTION
**Pull request by actuallyakash**
## Description
Added a switch named `Mark Favorite` under `Single Lesson Actions`.

## How has this been tested?
Manually.

## Types of changes
New feature

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
This still requires, to me, the logic to not display the favorite button in the lesson preview (syllabus and navigation)
see https://github.com/gocodebox/lifterlms-labs/pull/34#issuecomment-1502914388

I don't think the action validation is a good solution:
https://github.com/actuallyakash/lifterlms/commit/afd5b4e431e25b257cf216e62b9bfdc2b3a94e20#commitcomment-108633842

**Comment by actuallyakash** [comment]
@eri-trabiccolo 

Just pushed fixes according to the feedback. Thanks!

**Comment by eri-trabiccolo** [comment]
should be addressed when the [Favorite feature](https://github.com/gocodebox/lifterlms/pull/2384) is merged into core

**Comment by eri-trabiccolo** [comment]
closed in favor of #46 
also because of some changes in the logic of the favorite templating.

**Pull request closed without merging**
