### PR TITLE
Added switch for favorites.

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
Originally made by @actuallyakash here: https://github.com/gocodebox/lifterlms-labs/pull/31

## Description
Added a switch named `Mark Favorite` under `Single Lesson Actions`.

## How has this been tested?
Manually.

## Screenshots
image

## Types of changes
New feature

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
@actuallyakash see https://github.com/gocodebox/lifterlms-labs/pull/31#discussion_r1160731293
continue on this branch then! <3

**Comment by eri-trabiccolo** [comment]
Accidentally closed.
Please @actuallyakash continue here ❤️

**Comment by actuallyakash** [comment]
This is done, thanks for correcting the branch ❤️

**Comment by eri-trabiccolo** [comment]
@actuallyakash 
I see you now show the favorite button icon on the lesson preview in the syllabus.
If we have an option to remove it from the single lesson, I think we need an option to remove it from the syllbaus too, what do you think?

In any case, at the moment I'm the author of this PR, but I think you should be the author here so can you please re-open this PR? 
Thanks!

**Comment by actuallyakash** [comment]
Sure @eri-trabiccolo, I'll do that. 👍

**Comment by actuallyakash** [comment]
@eri-trabiccolo 

Action validation has been added in LifterLMS https://github.com/actuallyakash/lifterlms/commit/afd5b4e431e25b257cf216e62b9bfdc2b3a94e20

**Comment by eri-trabiccolo** [comment]
@actuallyakash can you open a new PR?
https://github.com/gocodebox/lifterlms-labs/compare/dev...feature/favorites?expand=1

We just need to be you the author of it :D
Thanks!

**Comment by actuallyakash** [comment]
Done. Thanks.
https://github.com/gocodebox/lifterlms-labs/pull/37

**Pull request closed without merging**
